config/routes.rb
TomblurBlogApp::Application.routes.draw do

  root to: "home#index"

  resources :users, :sessions

  resources :posts do
    resources :comments
  end

  resources :photos do
    resources :comments
  end

  get 'signup' => 'users#new'
  get 'signin' => 'sessions#new'
  get 'signout' => 'sessions#destroy'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :text, :commentable_id, :commentable_type, :user_id

  belongs_to :commentable, polymorphic: true
  belongs_to :user

  has_many :comments, as: :commentable

  validates :text, presence: true
  validates :commentable, presence: true
  validates :user_id, presence: true

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :title, :body, :image

  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
  validates :image, presence: true
  validates :user, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :body

  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true
  validates :user, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :username, :password_confirmation
  has_secure_password

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  validates :password_confirmation, presence: true
  validates :password, length: { minimum: 6 }
  validates_presence_of :email, :username, :password_confirmation
  validates_uniqueness_of :email, :username

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }

  private

  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/comments_controller.rb
require 'pry'

class CommentsController < ApplicationController
  def index

    if params[:post_id]
      @model = Post.find(params[:post_id])
    elsif params[:photo_id]
      @model = Photo.find(params[:photo_id])
    end

    @model = @model.comments
  end

  def new
    if params[:post_id]
      @model = Post.find(params[:post_id])
    elsif params[:photo_id]
      @model = Photo.find(params[:photo_id])
    end
    # raise @model.inspect
  end

  def create
    # binding.pry
    if params[:post_id]
      @model = Post.find(params[:post_id])
      @model.comments.create(params[:comment])
      redirect_to posts_path

    elsif params[:photo_id]
      @model = Photo.find(params[:photo_id])
      @model.comments.create(params[:comment])
      redirect_to photos_path

    end

  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

    @posts = Post.all
    # @post = Post.find(params[:post_id])
    @photos = Photo.all
    # @photo = Photo.find(params[:photo_id])
    @comments = Comment.all

    # if params[:post_id]
    #   @model = Post.find(params[:post_id])
    # elsif params[:photo_id]
    #   @model = Photo.find(params[:photo_id])
    # end

    # @model = @model.comments
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.all
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def new
    @photo = Photo.new
  end

  def create
    photo = Photo.new(params[:photo])
    photo.user = current_user
      photo.save
    render :json => {title: photo.title, body: photo.body image: photo.image user_id: photo.user_id}
    redirect_to photos_path
  end

  def update
  end

  def destroy
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.new(params[:post])
    post.user = current_user
      post.save
    render :json => {title: post.title, body: post.body, user_id: post.user_id}
    redirect_to posts_path
  end

  def update
  end

  def destroy
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to posts_path
    else
      flash.now[:error] = "Invalid email or password"
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in(@user)
      redirect_to posts_path
    else
      flash[:error] = @user.errors.messages
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to posts_path
    else
      flash[:error] = @user.errors.full_messages
      render :edit
    end
  end

  def destroy
    user = User.find(params[:id])
    user.delete
    redirect_to posts_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<%= form_for ([@model, @model.comments.build]) do |f| %>
  <%= f.text_area :text, placeholder: "comment"%> <br>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.submit %>
<% end %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<h2>Text Posts</h2>
<h3><%= link_to "New Post", new_post_path %></h3>
<ol>
  <% @posts.each do |post| %>

    <li>
      <p>Title: <a href="/posts/<%=post.id%>" ><%= post.title %></a></p>
      <p>Post: <%= post.body %></p>
      <p>Comments: <a href="/posts/<%=post.id%>/comments">Comments</a></p>
    </li>
  <% end %>
</ol>

<h2>Photo Posts</h2>
<h3><%= link_to "New Photo", new_photo_path %></h3>
<ol>
  <% @photos.each do |photo| %>
    <li>
      <p>Title: <%= photo.title %></p>
      <p>Desc: <%= photo.body %></p>
      <p>Photo: <img src="<%= photo.image %>" alt="photo" height="200px"></p>
  </li>
<% end %>
</ol>

<!-- if @model.class.to_s == "xx " -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tomblur</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

<% if current_user != nil %>
  <p><%= link_to "Sign out", signout_path%></p>
<% else %>
  <p><%= link_to "User Sign in/up", signin_path%></p>
<% end %>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/photos/_form.html.erb
<%= form_for (@photo, :remote => true) do |f| %>
  Title: <%= f.text_field :title  %> <br/>
  Post: <%= f.text_field :body, :required => true  %> <br/>
  Image: <%= f.text_field :image, :required => true  %> <br/>
  <%= f.submit "Create" %>
<% end %>

app/views/photos/index.html.erb
<h3><%= link_to "New Photo", new_photo_path %></h3>
<ol>
  <% @photos.each do |photo| %>
    <li>
      <p>Title:<%= photo.title %> </p>
      <p>Description:<%= photo.body %> </p>
      <p>Picture:<img src="<%= photo.image %>" alt="photo" height="300px"></p>
  </li>
<% end %>
</ol>

app/views/photos/new.html.erb
<%= render 'form' %>

app/views/photos/show.html.erb
<%= @photo.inspect %>

<!--
<% @post.each do |post| %>
  <%= render 'image_post', post: post %>
<% end %>
-->

app/views/posts/_form.html.erb
<%= form_for (@post, :remote => true) do |f| %>
  Title: <%= f.text_field :title  %> <br/>
  Post: <%= f.text_field :body, :required => true  %> <br/>
  <%= f.submit "Create" %>
<% end %>

app/views/posts/index.html.erb
<h3><%= link_to "New Post", new_post_path %></h3>
<ol>
  <% @posts.each do |post| %>
    <li>
      <p>Title:<a href="/posts/<%=post.id%>" ><%= post.title %></a></p>
      <p>Post:<%= post.body %></p>
      <p>Comments: </p>
      <% post.comments.each do |comment| %>
      <p><%= comment.text %><p>
      <% end %>
    </li>
  <% end %>
</ol>

app/views/posts/new.html.erb
<%= render "form" %>

app/views/posts/show.html.erb
<%= @post.title%> <br>
<%= @post.body%>
<%= link_to "New Comment", new_post_comment_path(@post.id) %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit "Create my Account", class: "btn btn-large btn-primary" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Your Account</h1>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit "Create my Account", class: "btn btn-large btn-primary" %>
  </div>
<% end %><h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/new.html.erb
<h1> Create a new Account </h1>

<%= render 'form' %>